# Overview
Hurricanes can be very damaging in terms of life and cost as we have seen during the year 2017, when hurricanes like Harvey, Irma and Maria caused pandemonium in the Atlantic Basin. We have compiled from Wikipedia a list of the costliest hurricanes in the Atlantic. This data can give us insights on which have been the most costly hurricanes, the busiest seasons, and the areas that have been affected the most.

# Data & Setup
The data has been collected from https://en.wikipedia.org/wiki/List_of_costliest_Atlantic_hurricanes. The data from 2017 has not been published yet, so it's not included in this dataset

In [3]:
import pandas as pd
import numpy as np

df1 = pd.read_html('https://en.wikipedia.org/wiki/List_of_costliest_Atlantic_hurricanes')
df = df1[0].drop(df1[0].index[0]).drop(5, axis=1)
df.columns = ['Name','Cost in Billions','Season','Classification','Areas Affected']
df['Classification']=df['Classification'].apply(lambda x: str(x)[3:]).apply(lambda x: x.strip()).replace('\xa0',' ',regex=True)
df['Cost in Billions']=df['Cost in Billions'].apply(lambda x: str(x)[1:]).apply(pd.to_numeric)
df

,Name,Cost in Billions,Season,Classification,Areas Affected
1,Katrina,108.000,2005,Category 5 hurricane,The Bahamas Florida United States Gulf Coast O...
2,Sandy,75.000,2012,Category 3 hurricane,The Caribbean United States East Coast Eastern...
3,Ike,37.500,2008,Category 4 hurricane,Greater Antilles Texas Louisiana Midwestern Un...
4,Wilma,29.400,2005,Category 5 hurricane,Greater Antilles Central America Florida
5,Andrew,26.500,1992,Category 5 hurricane,The Bahamas Florida United States Gulf Coast
6,Ivan,23.300,2004,Category 5 hurricane,The Caribbean Venezuela United States Gulf Coast
7,Irene,16.600,2011,Category 3 hurricane,The Caribbean United States East Coast Eastern...
8,Charley,16.300,2004,Category 4 hurricane,Jamaica Cayman Islands Cuba Florida The Carolinas
9,Matthew,15.090,2016,Category 5 hurricane,Colombia Venezuela The Caribbean United States...
10,Rita,12.000,2005,Category 5 hurricane,Cuba United States Gulf Coast
11,Hugo,10.000,1989,Category 5 hurricane,The Caribbean United States East Coast
12,Frances,9.800,2004,Category 4 hurricane,The Caribbean Eastern United States Ontario
13,Georges,9.720,1998,Category 4 hurricane,The Caribbean United States Gulf Coast
14,Allison,9.000,2001,Tropical storm,Texas Louisiana Southern United States
15,Jeanne,7.660,2004,Category 3 hurricane,The Caribbean Eastern United States
16,Gilbert,7.100,1988,Category 5 hurricane,Venezuela Central America Hispaniola Mexico
17,Floyd,6.900,1999,Category 4 hurricane,The Bahamas Eastern United States Atlantic Canada
18,Gustav,6.610,2008,Category 4 hurricane,Hispaniola Jamaica Cuba United States Gulf Coast
19,Mitch,6.200,1998,Category 5 hurricane,Central America Yucatán Peninsula South Florida
20,Isabel,5.370,2003,Category 5 hurricane,Greater Antilles The Bahamas Eastern United St...
21,Opal,5.100,1995,Category 4 hurricane,Guatemala Yucatán Peninsula Eastern United States
22,Stan,3.960,2005,Category 1 hurricane,Mexico Central America
23,Karl,3.900,2010,Category 3 hurricane,Mexico Central America
24,Dennis,3.710,2005,Category 4 hurricane,Greater Antilles Southeastern United States
25,Fran,3.200,1996,Category 3 hurricane,Eastern United States Ontario
26,Luis,3.000,1995,Category 4 hurricane,Leeward Islands Puerto Rico Bermuda
27,Marilyn,2.500,1995,Category 3 hurricane,The Caribbean Bermuda
28,Lee,2.500,2011,Tropical storm,United States East Coast
29,Isaac,2.390,2012,Category 1 hurricane,The Caribbean Eastern United States
30,Frederic,2.300,1979,Category 4 hurricane,The Caribbean Southeastern United States
31,Agnes,2.100,1972,Category 1 hurricane,Mexico Cuba Eastern United States
32,Joan,2.000,1988,Category 4 hurricane,Lesser Antilles Colombia Venezuela Central Ame...
33,Michelle,2.000,2001,Category 4 hurricane,Central America Jamaica Cuba The Bahamas
34,Alex,1.885,2010,Category 2 hurricane,Central America Greater Antilles Texas
35,Fifi,1.800,1974,Category 2 hurricane,Jamaica Central America Mexico
36,Dean,1.780,2007,Category 5 hurricane,The Caribbean Central America
37,Alicia,1.700,1983,Category 3 hurricane,East Texas Louisiana
38,David,1.540,1979,Category 5 hurricane,The Caribbean United States East Coast
39,Juan,1.500,1985,Category 1 hurricane,United States Gulf Coast
40,Bob,1.500,1991,Category 3 hurricane,United States East Coast Canada
41,Roxanne,1.500,1995,Category 3 hurricane,Mexico
42,Ingrid,1.500,2013,Category 1 hurricane,Mexico
43,Betsy,1.450,1965,Category 4 hurricane,The Caribbean Southeastern United States
44,Camille,1.420,1969,Category 5 hurricane,Cuba United States Gulf Coast
45,Dolly,1.350,2008,Category 2 hurricane,Cayman Islands Mexico Southwestern United States
46,Elena,1.300,1985,Category 3 hurricane,Cuba United States Gulf Coast
47,Isidore,1.300,2002,Category 3 hurricane,Cuba Yucatán Peninsula Louisiana
48,Allen,1.240,1980,Category 5 hurricane,The Caribbean Yucatán Peninsula Mexico South T...
49,Emily,1.014,2005,Category 5 hurricane,Guyana Colombia The Caribbean Honduras Belize ...
50,Beulah,1.000,1967,Category 5 hurricane,The Caribbean Mexico Texas
51,Alberto,1.000,1994,Tropical storm,Southeastern United States

In [4]:
# list the 10 most costly hurricanes and their season
# it should return a dataframe with two columns: the name of the hurricane and the season
def question1():
    data = df
    return "Answer" # put your answer here

In [6]:
# find the four seasons with the most hurricanes on this list: 
# return a dataset of size 4 with an index of 
# season, and a value of number of hurricanes for that season
# ordered from most hurricanes to least hurricanes:
# e.g
# 2005  6
# 2012  2
# ... 
def question2():
    data = df
    return "Answer" # put your answer here

In [8]:
# compare the cost of the damage caused by the hurricanes for Cuba, 
# Mexico and United States.
# return a tuple with the three countries in order from more cost sustained
# by hurricane damage to less cost sustained
# e.g ('United States','Mexico','Cuba')
# you can manually build the tuple based on the results
# tip: you can use str.contains to look for that country string in the 'Areas Affected' column
def question3():
    data = df
    return "Answer" # put your answer here

In [10]:
#List the four seasons which were most costly along with its associated cost
#put your results in a series where the index is the season and the value is the cost
# tip: you will need to use a groupby on the Season and then add the cost
def question4():
    data = df
    return "Answer" # put your answer here

In [12]:
# How much more costly were hurricanes of category 5 than hurricanes of category 4
# you result should be a single number representing the difference in billions
# tip: you'll need to use a groupby on the Classification column
def question5():
    data = df
    return "Answer" # put your answer here